Traceback (most recent call last):
  File "errorFile.py", line 3, in <module>
    raise Exception('The is the error message.')
Exception: The is the error message.
